name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        stack: [react, vue]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies, build, and publish
        run: |
          cd ${{ matrix.stack }}
          npm ci
          npm version ${{ github.event.release.tag_name }}
          npm run build
          npm pack
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
